#!/bin/bash
# Einrichtungsskript für AdBlockSettings

# Gemeinsame Ressourcen laden
source /data/SetupHelper/CommonResources

# Standardaktionen aktivieren
standardPromptAndActions='yes'

# Installationsverzeichnis festlegen
ROOT_PATH=/data/AdBlockSettings

# Funktion, symlink zu rc.local hinzuzufügen
add_symlink_entry_to_rc_local() {
    local RC_LOCAL_PATH="/data/rc.local"
    local ENTRY="ln -s /data/AdBlockSettings/service/AdBlockSettings /service/AdBlockSettings"

    [ ! -f "$RC_LOCAL_PATH" ] && echo "$ENTRY" > "$RC_LOCAL_PATH" || [ ! "$(grep "$ENTRY" "$RC_LOCAL_PATH")" ] && echo "$ENTRY" >> "$RC_LOCAL_PATH"
    chmod +x "$RC_LOCAL_PATH"
}

# Funktion, symlink aus rc.local zu entfernen
remove_symlink_entry_from_rc_local() {
    local RC_LOCAL_PATH="/data/rc.local"
    local ENTRY="ln -s /data/AdBlockSettings/service/AdBlockSettings /service/AdBlockSettings"

    [ -f "$RC_LOCAL_PATH" ] && sed -i "/^$(echo "$ENTRY" | sed 's/[\/&]/\\&/g')$/d" "$RC_LOCAL_PATH"
}

# Funktion, um den dnsmasq-Starteintrag zu rc.local hinzuzufügen
add_dnsmasq_entry_to_rc_local() {
    local RC_LOCAL_PATH="/data/rc.local"
    local ENTRY="/etc/init.d/dnsmasq start"

    [ ! -f "$RC_LOCAL_PATH" ] && echo "$ENTRY" > "$RC_LOCAL_PATH" || [ ! "$(grep "$ENTRY" "$RC_LOCAL_PATH")" ] && echo "$ENTRY" >> "$RC_LOCAL_PATH"
    chmod +x "$RC_LOCAL_PATH"
}

# Funktion, um den dnsmasq-Starteintrag aus rc.local zu entfernen
remove_dnsmasq_entry_from_rc_local() {
    local RC_LOCAL_PATH="/data/rc.local"
    local ENTRY="/etc/init.d/dnsmasq start"

    [ -f "$RC_LOCAL_PATH" ] && sed -i "/^$(echo "$ENTRY" | sed 's/[\/&]/\\&/g')$/d" "$RC_LOCAL_PATH"
}

# Funktion, um das GUI und den Patch zu überprüfen
check_gui_and_patch() {
    local QML_PATH="/opt/victronenergy/gui/qml/PageSettingsAdBlock.qml"
    local PATCH_PATH="/opt/victronenergy/gui/qml/PageSettings.qml"
    local PATCH_SOURCE="/data/AdBlockSettings/FileSets/PatchSource/PageSettings.qml.patch"

    if [ ! -f "$QML_PATH" ] || ! grep -q "//////// modified to insert AdBlockSettings menu" "$PATCH_PATH"; then
        perform_installation
    fi
}

# Funktion, um den Patch anzuwenden
apply_adblock_patch() {
    local PATCH_PATH="/opt/victronenergy/gui/qml/PageSettings.qml"
    local PATCH_SOURCE="/data/AdBlockSettings/FileSets/PatchSource/PageSettings.qml.patch"

    if ! grep -q "//////// modified to insert AdBlockSettings menu" "$PATCH_PATH"; then
        patch "$PATCH_PATH" < "$PATCH_SOURCE"
    fi
}

# Installationsroutine
perform_installation() {
    logMessage "Installation beginnt..."
    # Erstellen Sie D-Bus-Einstellungspfade mit Standardwerten
    addAllDbusSettings

    # symlink zu rc.local hinzuzufügen
    add_symlink_entry_to_rc_local

    # dnsmasq-Starteintrag zu rc.local hinzufügen
    add_dnsmasq_entry_to_rc_local

    # Neue QML-Dateien kopieren, überschreibt vorhandene Dateien
    cp -f /data/AdBlockSettings/FileSets/VersionIndependent/*.qml /opt/victronenergy/gui/qml/

    # Patch anwenden
    apply_adblock_patch

    cp -f /data/AdBlockSettings/FileSets/configs/dnsmasq_static.conf /etc/dnsmasq_static.conf

    # Variablen für den SetupHelper setzen
    restartGuiNeeded=true
}

# Deinstallationsroutine
perform_uninstallation() {
    logMessage "Deinstallation beginnt..."

    # symlink aus rc.local zu entfernen
    remove_symlink_entry_from_rc_local
    
    # dnsmasq-Starteintrag aus rc.local entfernen
    remove_dnsmasq_entry_from_rc_local

    # Hinzugefügte QML-Dateien von AdBlockSettings entfernen
    rm -f /opt/victronenergy/gui/qml/PageSettingsAdBlock.qml

    # Original dnsmasq.conf wiederherstellen
    [ -f "/etc/dnsmasq.conf.orig" ] && mv /etc/dnsmasq.conf.orig /etc/dnsmasq.conf

    # dnsmasq neu starten
    /etc/init.d/dnsmasq restart

    logMessage "Deinstallation abgeschlossen."
    restartGuiNeeded=true
}

# Ausführung basierend auf der angegebenen Aktion
case "$scriptAction" in
    INSTALL)
        perform_installation
        ;;
    UNINSTALL)
        perform_uninstallation
        ;;
    CHECK)
        check_gui_and_patch
        ;;
    *)
        logMessage "Unbekannte Aktion: $scriptAction. Beende Skript."
        exit 1
        ;;
esac

logMessage "Skriptausführung abgeschlossen."

# Setzen der Statusvariablen für den SetupHelper
endScript
